language: node_js
node_js:
  - 10.15

services:
  - mongodb

env:
  - DB_TEST="mongodb://localhost:27017/pokemondb_test"

cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn build